

import { Html, Head, Main, NextScript } from "next/document";
import React, { ReactElement } from "react";
//import "@/styles/globals.css";
import "./globals.css";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import Header from "../components/header/Header";
import HeaderBottom from "../components/header/HeaderBottom";
import Footer from "../components/Footer";
import App from "./_app";
import { Providers } from "./providers";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-bodyFont dark:bg-gray-900">
       <Providers>
        <Header/>
        <HeaderBottom/>
        {children}
        <Footer/></Providers>
      </body> 
    </html>
        
  );
}
/*
 <Html lang="en">
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
    */